name: Docker
on:
  push:
    branches:
      - "master"
      - "develop/**"
      - "releases/**"
      - "features/**"
  pull_request:
    branches: ["master", "stagging"]
jobs:
  build:
    name: "Push Docker image to Docker Hub"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag alexandrelamberty/nidus-api:${{ env.BRANCH }}

      - name: Docker Push
        run: docker push alexandrelamberty/nidus-api
